### ISSUE TITLE
Training dataset format

### ISSUE THREAD

**Issue by marcelo-bn** [markub3327/Solar-Transformer#1]
Hello!

Can you give a example of the training dataset format?

For example, did you use it like this?

X = [[x_1, x_2, x_3], ..., [x_n1,x_n2,x_n3]]
Y = [[y_1], ..., [y_n]]

where x_1, x_2, x_3 are temperature, humidity and wind speed (this feature are just for the example)
and y_n is the value of the solar irradiance for each tuple of x.

Thank you for your attention!

**Comment by markub3327** [comment]
Hello.

The dataset is my own CSV file generated by https://github.com/markub3327/NASA-POWER-BOT.

The input is region - daily solar irradiance.
**The columns are:**
time = yyyymmddHH
irradiance = features1[f1]["properties"]["parameter"]["ALLSKY_SFC_SW_DWN"]
temp = features1[f1]["properties"]["parameter"]["T2M"]
temp_min = features1[f1]["properties"]["parameter"]["T2M_MIN"]
temp_max = features1[f1]["properties"]["parameter"]["T2M_MAX"]
humidity = features1[f1]["properties"]["parameter"]["RH2M"]
wind_speed = features2[f2]["properties"]["parameter"]["WS10M"]
wind_speed_min = features2[f2]["properties"]["parameter"]["WS10M_MIN"]
wind_speed_max = features2[f2]["properties"]["parameter"]["WS10M_MAX"]
wind_direction = features2[f2]["properties"]["parameter"]["WD10M"]
pressure = features2[f2]["properties"]["parameter"]["PS"]

The predicted y is point - daily solar irradiance.
**The columns are:**
time = yyyymmddHH
long_name = data_point_hourly["parameters"]["ALLSKY_SFC_SW_DWN"]["longname"]
units = data_point_hourly["parameters"]["ALLSKY_SFC_SW_DWN"]["units"]
fill_value_point_hourly = data_point_hourly["header"]["fill_value"]
irradiance = data_point_hourly["properties"]["parameter"]["ALLSKY_SFC_SW_DWN"]
